spring.application.name=BackEnd




spring.neo4j.uri=
spring.neo4j.authentication.username=
spring.neo4j.database=
spring.neo4j.authentication.password=



spring.neo4j.warn-on-deprecated-queries=false

logging.level.org.springframework.data.neo4j=ERROR
logging.level.org.neo4j.driver=ERROR


server.port=8080

spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true


spring.main.allow-bean-definition-overriding=true











